# Generated by django-object-streams.

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("object_streams", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjectStreamOutboxState",
            fields=[
                ("id", models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ("pruned_through", models.BigIntegerField(default=0)),
            ],
        ),
    ]
