# Generated by django-object-streams.

from django.db import migrations
from django.db import models


def initialize_delivery_cursors(apps, schema_editor):
    ObjectStreamEvent = apps.get_model("object_streams", "ObjectStreamEvent")
    ObjectStreamOutboxState = apps.get_model("object_streams", "ObjectStreamOutboxState")
    database = schema_editor.connection.alias
    manager = ObjectStreamEvent.objects.using(database)
    manager.update(cursor=models.F("id"))
    latest = manager.order_by("-cursor").values_list("cursor", flat=True).first() or 0
    ObjectStreamOutboxState.objects.using(database).update_or_create(
        pk=1,
        defaults={
            "next_cursor": latest + 1,
            "broadcasted_through": latest,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("object_streams", "0002_objectstreamoutboxstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="objectstreamevent",
            name="cursor",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="objectstreamoutboxstate",
            name="broadcasted_through",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="objectstreamoutboxstate",
            name="next_cursor",
            field=models.BigIntegerField(default=1),
        ),
        migrations.RunPython(initialize_delivery_cursors, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="objectstreamevent",
            name="cursor",
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterModelOptions(
            name="objectstreamevent",
            options={"ordering": ["cursor", "id"]},
        ),
        migrations.RemoveIndex(
            model_name="objectstreamevent",
            name="object_stre_subject_4c6a07_idx",
        ),
        migrations.RemoveIndex(
            model_name="objectstreamevent",
            name="object_stre_facet_327c88_idx",
        ),
        migrations.AddIndex(
            model_name="objectstreamevent",
            index=models.Index(
                fields=["subject_content_type", "subject_object_id", "cursor"],
                name="object_stre_subject_8d65d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="objectstreamevent",
            index=models.Index(fields=["facet", "cursor"], name="object_stre_facet_407b73_idx"),
        ),
    ]
